version: "3.8"

services:
    frontend:
        build:
            context: ./frontend
            dockerfile: ./Dockerfile.front
        ports:
            - 3000:3000
        networks:
            - app-network
        depends_on:
            - backend

    backend:
        build:
            context: ./backend
            dockerfile: ./Dockerfile.back
        ports:
            - 8000:8000
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
