# Dockerfile.backend
FROM python:3.10-slim-bullseye
RUN apt-get update && apt-get install -y build-essential
WORKDIR /app
COPY ./backend .
RUN pip install -r requirements.txt
EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]